[package]
name = "advanced-with-resonator-integration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terrasound = "0.2.0"
resonator = "0.2.0"